### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by nickbeaulieu98** [kodymallory/MMM-withings#1]
I've created a tokens.json file with my code and it just gives me this repeatedly:

No Access Token Found, Trying code...
Code is  b896649706cf87319b4a475c064d4ca01120f7ca
Generating Access tokens...
{ errors: [ { message: 'invalid_grant: Invalid Params: invalid code' } ] }
[ { message: 'invalid_grant: Invalid Params: invalid code' } ]

I've re-created the code but that I keep getting the same error.

**Comment by ccopol** [comment]
I didn't succeed with this way either.  What I did:
- Callback URI is a php that prints the token
- Copy the token and write in tokens.json

```json
{"access_token":"aebaeae45678uajldsgq",
"refresh_token":"8765TSLJDpie"
}
```

**Comment by fabbr** [comment]
I also noticed that the file was missing. I created it and I was not able to make the module work. 

Any hope on getting this fix? This is a fantastic idea to have that on your mirror and will motive us to stay healthy

Thank you for your time @kodymallory

**Comment by ccopol** [comment]
You have to create the file. It's normal. Did you get the authentication code ? Please note the code is valid for only 30s.

**Comment by kodymallory** [comment]
Hi all. Thanks for the interest. Sorry the auth process has been a pain. I am wrapping up a move across country for the last two months and have not had time to look at clarifying this and making it simpler. Hope to get to it in the next month or two as I get all my equipment back out of storage. Like at @ccopol said you only have 30s.

**Comment by fabbr** [comment]
@ccopol So, for you solution the tokens.json file will have those two values instead of code, correct? 

Where can I get those values? access_token and refresh_token? from the page I get on when going to URL on step 7? 


@kodymallory Thank you very much for your time and effort into putting this together!

**Comment by ccopol** [comment]
@kodymallory I don't know if it's possible to make it simpler. I think there is a problem when the module request the tokens for the first time. I admit I didn't look for.

@fabbr Yes. Instead of the auth code, you can put your tokens. Your will need
- `curl` install (on the pi or on your computer)
- your `client_id`,
- your `client_secret`
- your redirect_uri
- and your `code`

When you have all these, on a terminal type:
```bash
curl --data "grant_type=authorization_code&client_id=[STRING]&client_secret=[STRING]&code=[STRING]&redirect_uri=[STRING]" 'https://account.withings.com/oauth2/token'
```

*Please* replace `[STRING]` by the correct value. Because you only have 30s, prepare the command before to request an auth code.

**Comment by fabbr** [comment]
> @kodymallory I don't know if it's possible to make it simpler. I think there is a problem when the module request the tokens for the first time. I admit I didn't look for.
> 
> @fabbr Yes. Instead of the auth code, you can put your tokens. Your will need
> 
> * `curl` install (on the pi or on your computer)
> * your `client_id`,
> * your `client_secret`
> * your redirect_uri
> * and your `code`
> 
> When you have all these, on a terminal type:
> 
> ```shell
> curl --data "grant_type=authorization_code&client_id=[STRING]&client_secret=[STRING]&code=[STRING]&redirect_uri=[STRING]" 'https://account.withings.com/oauth2/token'
> ```
> 
> _Please_ replace `[STRING]` by the correct value. Because you only have 30s, prepare the command before to request an auth code.


Perfect. 

The redirect_uri is https://account.health.nokia.com/oauth2_user/authorize2?response_type=code&redirect_uri=https://example.com&scope=user.info,user.metrics,user.activity&state=1&client_id=<STRING>

Where string is my ID, correct? 

And the code is the one I grab from the URL after I click in the redirect URI, correct? 

I tried with those assumptions and got 
`{"errors":[{"message":"invalid_grant: Invalid Params: invalid code"}]}`

Thank you so much for your time on helping me out. I hope this will also help others.

**Comment by fabbr** [comment]
> @kodymallory I don't know if it's possible to make it simpler. I think there is a problem when the module request the tokens for the first time. I admit I didn't look for.
> 
> @fabbr Yes. Instead of the auth code, you can put your tokens. Your will need
> 
> * `curl` install (on the pi or on your computer)
> * your `client_id`,
> * your `client_secret`
> * your redirect_uri
> * and your `code`
> 
> When you have all these, on a terminal type:
> 
> ```shell
> curl --data "grant_type=authorization_code&client_id=[STRING]&client_secret=[STRING]&code=[STRING]&redirect_uri=[STRING]" 'https://account.withings.com/oauth2/token'
> ```
> 
> _Please_ replace `[STRING]` by the correct value. Because you only have 30s, prepare the command before to request an auth code.

Thank you, Looks like that works. I am not sure if it's updating tho. I will test it out. 

Do you know if I have to do this every time I restart the Mirror? 

Thanks again for your time.

**Comment by ccopol** [comment]
No, just once. The module will refresh the tokens.

Glad it works

**Comment by RichardHerold** [comment]
I had trouble keeping up with everything above so I figure I'd post this summary to help people in the future.

1. follow the instructions in the readme til you authorize your application
2. follow ccpol's trick to get the tokens

> @fabbr Yes. Instead of the auth code, you can put your tokens. Your will need
> 
> * `curl` install (on the pi or on your computer)
> * your `client_id`,
> * your `client_secret`
> * your redirect_uri
> * and your `code`
> 
> When you have all these, on a terminal type:
> 
> ```shell
> curl --data "grant_type=authorization_code&client_id=[STRING]&client_secret=[STRING]&code=[STRING]&redirect_uri=[STRING]" 'https://account.withings.com/oauth2/token'
> ```
> 
> _Please_ replace `[STRING]` by the correct value. Because you only have 30s, prepare the command before to request an auth code.

3. copy ccpol's advice to create a file tokens.json in the MMM-withings directory replacing his codes with your own.


> I didn't succeed with this way either. What I did:
> 
> * Callback URI is a php that prints the token
> * Copy the token and write in tokens.json
> 
> ```json
> {"access_token":"aebaeae45678uajldsgq",
> "refresh_token":"8765TSLJDpie"
> }
> ```

that got it working for me! 

Also of note: I had a black screen when i did all of this and it seemed like magic mirror wasn't working anymore.

this helped me get my screen back

'''cd ~/MagicMirror
git checkout modules/node_modules/node_helper/index.js'''

**Comment by e87genius** [comment]
I followed the steps but I'm stuck on step 2 to get the Tokens.  I entered this into the Terminal (with the correct redirect_uri):

curl --data “grant_type=authorization_code&client_id=3f5042789cf22b609fa1fd780a2009c0732a0286dd42a571c7bf35bd95b2b337&client_secret=430706c5be37c8350bfe93e033fb29067a034c51ee05b8d7b909cea1d44ac057&code=18b901b94caf62e9de239077b060fbe34241ca3f&redirect_uri=[STING]” -x POST https://account.withings.com/oauth2/token

but the Terminal returns the error.  The error is:

[3] 14755
[4] 14756
[5] 14757
[6] 14758
-bash: https://account.withings.com/oauth2/token: No such file or directory
[2]   Exit 2                  curl --data “grant_type=authorization_code
[4]   Done                    client_id=3f5042789cf22b609fa1fd780a2009c0732a0286dd42a571c7bf35bd95b2b337
[5]-  Done                    client_secret=430706c5be37c8350bfe93e033fb29067a034c51ee05b8d7b909cea1d44ac057
[6]+  Done                    code=18b901b94caf62e9de239077b060fbe34241ca3f

**Comment by e87genius** [comment]
Step 2 returns an error on the terminal.  When I type in (my ### replacing the the [STRING] labels):
curl --data "grant_type=authorization_code&client_id=[STRING]&client_secret=[STRING]&code=[STRING]&redirect_uri=[STRING]" 'https://account.withings.com/oauth2/token'

the terminal returns:
[222] 5104
[223] 5105
[224] 5106
[225] 5107
-bash: https://account.withings.com/oauth2/token: No such file or directory
[221]   Exit 2                  curl -d “grant_type=authorization_code
[223]   Done                    client_id=###
[224]   Done                    client_secret=###
[225]   Done                    code=###

Can someone post some advice?

**Comment by Allocdk** [comment]
Got it working thanks.

But, is there any way i can change the text? It shows the numbers in the correct unit (kg) but the text still says lbs

**Comment by kodymallory** [comment]
@fabbr and @ccopol I made a modification to authenticate automatically.

This instead uses the app credentials I created, and then if unable to authenticate, pops open a browser to request authorization and auto handles the token negotiation after the user logs in and grants access. The response_uri is to the localhost, and will post a GET request to a simple server running within the module.

I am running this on a Raspberry Pi and it seems to work. Would you be willing to try it out? I created a pull request #4 if you want to give it a try.

**Comment by nickbeaulieu98** [comment]
Been a long time since I worked on this project. Anyway, I got it working now thanks to @ccopol
