### ISSUE TITLE
Tokens.json

### ISSUE THREAD

**Issue by bouba830** [kodymallory/MMM-withings#8]
Hello, I can't find the Tokens.json file anywhere. can you orient me please?

**Comment by kodymallory** [comment]
The module uses a popup to connect authorization automatically now. You shouldn't need to modify the tokens.json file. If you do need it to follow the old method, you can just create a tokens.json file at the top level of the module.

**Comment by bouba830** [comment]
hello @kodymallory, thanks for your response: D,
indeed I have just checked and I have the latest version of the module, I followed the installation instructions step by step and when I launch MM a web page opens and then it asks me for permission to connect to my scale.
I think the pass I didn't understand is the callback address. how does it work?
I put redirectUri: "'https://example.com'," did I do it right?
thank you for your help and I wish you a happy Christmas

**Comment by kodymallory** [comment]
The part with the [callback ](https://github.com/kodymallory/MMM-withings#setting-up-api-key-and-user-account) is the less automated way of connecting it. I will modify the readme to account for that.

**Comment by kodymallory** [comment]
Had to pivot away from the automatic pop up. There is a limit of 10 users on the app if I use the localhost redirectUri which is necessary for the automatic popup. I have changed the readme to reflect that authorization should revert to the old steps. I will add a note to create the tokens.json file in the readme.

**Comment by kodymallory** [comment]
README now reflects instructions to create file if missing.
